INSERT INTO Photographer (id, name, city, country, tagline, price, portrait) VALUES (82, 'Tracy Galindo', 'Montreal', 'Canada', 'Photographe freelance', 500, 'TracyGalindo.jpg');
INSERT INTO Photographer (id, name, city, country, tagline, price, portrait) VALUES (195, 'Marcel Nikolic', 'Berlin', 'Germany', 'Toujours à la recherche de LA photo', 300, 'MarcelNikolic.jpg');
INSERT INTO Photographer (id, name, city, country, tagline, price, portrait) VALUES (243, 'Mimi Keel', 'London', 'UK', 'Voir le beau dans le quotidien', 400, 'MimiKeel.jpg');
INSERT INTO Photographer (id, name, city, country, tagline, price, portrait) VALUES (527, 'Nabeel Bradford', 'Mexico City', 'Mexico', 'Toujours aller en avant', 350, 'NabeelBradford.jpg');
INSERT INTO Photographer (id, name, city, country, tagline, price, portrait) VALUES (925, 'Rhode Dubois', 'Barcelona', 'Spain', 'Je crée des souvenirs', 275, 'RhodeDubois.jpg');
INSERT INTO Photographer (id, name, city, country, tagline, price, portrait) VALUES (930, 'Ellie-Rose Wilkens', 'Paris', 'France', 'Capturer des compositions complexes', 250, 'EllieRoseWilkens.jpg');
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (1, 82, 'Fashion Yellow Beach', 'Fashion_Yellow_Beach.jpg', NULL, 64, '2011-12-08', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (2, 82, 'Fashion Urban Jungle', 'Fashion_Urban_Jungle.jpg', NULL, 11, '2011-11-06', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (3, 82, 'Fashion Pattern on a Pattern', 'Fashion_Pattern_on_Pattern.jpg', NULL, 72, '2013-08-12', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (4, 82, 'Wedding Gazebo', 'Event_WeddingGazebo.jpg', NULL, 115, '2018-02-22', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (5, 82, 'Sparkles', 'Event_Sparklers.jpg', NULL, 5, '2020-05-25', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (6, 82, '18th Anniversary', 'Event_18thAnniversary.jpg', NULL, 34, '2019-06-12', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (7, 82, 'Wooden sculpture of a horse', NULL, 'Art_Wooden_Horse_Sculpture.mp4', 24, '2011-12-08', 100);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (8, 82, 'Triangle Man', 'Art_Triangle_Man.jpg', NULL, 88, '2007-05-07', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (9, 82, 'Purple Tunnel', 'Art_Purple_light.jpg', NULL, 25, '2018-05-05', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (10, 82, 'Art Mine', 'Art_Mine.jpg', NULL, 76, '2019-11-25', 55);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (11, 925, '8 Rows', 'Sport_2000_with_8.jpg', NULL, 52, '2013-02-30', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (12, 925, 'Fashion Wings', 'Fashion_Wings.jpg', NULL, 58, '2018-07-17', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (13, 925, 'Melody Red on Stripes', 'Fashion_Melody_Red_on_Stripes.jpg', NULL, 11, '2019-08-12', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (14, 925, 'Venture Conference', 'Event_VentureConference.jpg', NULL, 2, '2019-01-02', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (15, 925, 'Product Pitch', 'Event_ProductPitch.jpg', NULL, 3, '2019-05-20', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (16, 925, 'Musical Festival Keyboard', 'Event_KeyboardCheck.jpg', NULL, 52, '2019-07-18', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (17, 925, 'Musical Festival Singer', 'Event_Emcee.jpg', NULL, 23, '2018-02-22', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (18, 925, 'Animal Majesty', 'Animals_Majesty.jpg', NULL, 52, '2017-03-13', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (19, 925, 'Cute puppy on sunset', NULL, 'Animals_Puppiness.mp4', 52, '2016-06-12', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (20, 527, 'Rocky mountains from the air', NULL, 'Travel_Rock_Mountains.mp4', 23, '2017-03-18', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (21, 527, 'Outdoor Baths', 'Travel_Outdoor_Baths.jpg', NULL, 101, '2017-04-03', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (22, 527, 'Road into the Hill', 'Travel_Road_into_Hill.jpg', NULL, 99, '2018-04-30', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (23, 527, 'Bridge into the Forest', 'Travel_Bridge_into_Forest.jpg', NULL, 34, '2016-04-05', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (24, 527, 'Boat Wonderer', 'Travel_Boat_Wanderer.jpg', NULL, 23, '2017-03-18', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (25, 527, 'Portrait Sunkiss', 'Portrait_Sunkissed.jpg', NULL, 66, '2018-05-24', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (26, 527, 'Shaw Potrait', 'Portrait_Shaw.jpg', NULL, 52, '2017-04-21', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (27, 527, 'Alexandra', 'Portrait_Alexandra.jpg', NULL, 95, '2018-11-02', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (28, 527, 'Afternoon Break', 'Portrait_AfternoonBreak.jpg', NULL, 25, '2019-01-02', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (29, 243, 'Lonesome', 'Travel_Lonesome.jpg', NULL, 88, '2019-02-03', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (30, 243, 'Hillside Color', 'Travel_HillsideColor.jpg', NULL, 86, '2019-04-03', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (31, 243, 'Wednesday Potrait', 'Portrait_Wednesday.jpg', NULL, 34, '2019-04-07', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (32, 243, 'Nora Portrait', 'Portrait_Nora.jpg', NULL, 63, '2019-04-07', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (33, 243, 'Raw Black Portrait', 'Portrait_Background.jpg', NULL, 55, '2019-06-20', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (34, 243, 'Seaside Wedding', 'Event_SeasideWedding.jpg', NULL, 25, '2019-06-21', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (35, 243, 'Boulder Wedding', 'Event_PintoWedding.jpg', NULL, 52, '2019-06-25', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (36, 243, 'Benevides Wedding', 'Event_BenevidesWedding.jpg', NULL, 78, '2019-06-28', 45);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (37, 243, 'Wild horses in the mountains', NULL, 'Animals_Wild_Horses_in_the_mountains.mp4', 142, '2019-08-23', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (38, 243, 'Rainbow Bird', 'Animals_Rainbow.jpg', NULL, 59, '2019-07-02', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (39, 195, 'Japanese Tower, Kyoto', 'Travel_Tower.jpg', NULL, 68, '2019-04-03', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (40, 195, 'Senset on Canals, Venice', 'Travel_SunsetonCanals.jpg', NULL, 81, '2019-05-06', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (41, 195, 'Mountain and Lake', 'Travel_OpenMountain.jpg', NULL, 33, '2019-05-12', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (42, 195, 'City Bike and Stair, Paris', 'Travel_Bike_and_Stair.jpg', NULL, 53, '2019-06-20', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (43, 195, 'Adventure Door, India', 'Travel_Adventure_Door.jpg', NULL, 63, '2019-06-26', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (44, 195, 'Contrast, St Petersburg', 'Architecture_Contrast.jpg', NULL, 52, '2019-06-30', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (45, 195, 'On a Hill, Tibet', 'Architecture_On_a_hill.jpg', NULL, 65, '2019-07-20', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (46, 195, 'Leaning Tower, Pisa', 'Architecture_Dome.jpg', NULL, 88, '2020-01-05', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (47, 195, 'Drone shot of Buenos Aires highways', NULL, 'Architecture_coverr_circle_empty_highway_in_buenos_aires_587740985637.mp4', 57, '2020-01-20', 65);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (48, 195, 'Corner Building and Blue Sky', 'Architecture_Corner_Room.jpg', NULL, 54, '2020-05-05', 60);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (49, 930, 'Tricks in te air', NULL, 'Sport_Tricks_in_the_air.mp4', 150, '2018-02-30', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (50, 930, 'Climber', 'Sport_Next_Hold.jpg', NULL, 101, '2018-03-05', 65);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (51, 930, 'Surfer', 'sport_water_tunnel.jpg', NULL, 103, '2018-03-10', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (52, 930, 'Skier', 'Sport_Sky_Cross.jpg', NULL, 77, '2018-04-16', 50);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (53, 930, 'Race End', 'Sport_Race_End.jpg', NULL, 88, '2018-04-22', 65);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (54, 930, 'Jump!', 'Sport_Jump.jpg', NULL, 95, '2018-04-27', 70);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (55, 930, 'White Light', 'Architecture_White_Light.jpg', NULL, 52, '2018-05-03', 75);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (56, 930, 'Water on Modern Building', 'Architecture_Water_on_Modern.jpg', NULL, 55, '2018-05-10', 72);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (57, 930, 'Horseshoe', 'Architecture_Horseshoe.jpg', NULL, 85, '2018-05-15', 71);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (58, 930, 'Cross Bar', 'Architecture_Cross_Bar.jpg', NULL, 66, '2018-05-20', 58);
INSERT INTO Media (id, photographerId, title, image, video, likes, date, price) VALUES (59, 930, 'Connected Curves', 'Architecture_Connected_Curves.jpg', NULL, 79, '2018-05-21', 80);
