// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: 'tsx ./prisma/seed.js',
  },
  datasource: {
    url: "file:C:/Users/fouad/Documents/openclassroom/React_2025/react-p5/fisheye/prisma/dev.db",
  },
});